name: payment-processor
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- wai
- warp
- aeson
- time
- uuid
- containers
- bytestring
- text
- hashable
- hlint
- apply-refact

library:
  source-dirs: src
  exposed-modules:
  - Types
  - Storage
  - PaymentService
  - API
  - Handlers
  - Logger

executables:
  payment-processor:
    main: Main.hs
    source-dirs: src
    dependencies:
    - payment-processor